### ISSUE TITLE
Doesn't request Camera Permissions on Mobile

### ISSUE THREAD

**Issue by RandomArray** [kdzwinel/JS-OCR-demo#2]
Checking on the demo on my mobile phone (Android Nexus 5X) and not receiving a Camera Permission Request. Unable to initiate capture of picture.

**Comment by kdzwinel** [comment]
thanks for reporting, I heard some news about media API being changed, I bet that's it. I'll take a look this week

**Comment by kdzwinel** [comment]
Please make sure that you visited demo over HTTPS not HTTP. I've updated demo link in the readme.

**Comment by RandomArray** [comment]
Works great now. Thanks!

**Comment by kdzwinel** [comment]
HTTPS is now enforced by default
