### ISSUE TITLE
getUserMedia API needs HTTPS only

### ISSUE THREAD

**Issue by frontenddeveloping** [kdzwinel/JS-OCR-demo#3]
Chrome error:

> Mixed Content: The page at 'https://kdzwinel.github.io/JS-OCR-demo/' was loaded over HTTPS, but requested an insecure resource 'http://ghbtns.com/github-btn.html?user=kdzwinel&repo=JS-OCR-demo&type=watch&count=true'. This request has been blocked; the content must be served over HTTPS.

Security changes were released to Chrome, unsecured (HTTP) sites no longer able to implement voice, video.

**Comment by kdzwinel** [comment]
Hey, thanks for reporting - see #2 for solution.

**Comment by alejandri** [comment]
Hi very nice work. I cannot upload photo from cellphone, show me a black screen after take picture. Motorola G Version Android 4.4.4
Extra question: how I can uplod file jpg directly with a simple form? 
![12825390_10201292710557356_1850513641_n](https://cloud.githubusercontent.com/assets/3764626/13546984/deebfca8-e29d-11e5-8aa8-faf9d272f5bc.jpg)

**Comment by frontenddeveloping** [comment]
@alejandri if you will open remote console you will get the same error. I just create a fork.

**Comment by kdzwinel** [comment]
@alejandri please let me know what browser and which version you are using, I'll try to reproduce that. Please also make sure that you are on the https version of the website

@frontenddeveloping as far as I understand, there is no need to fix anything, just make sure to open the website via HTTPS. Am I right?

**Comment by frontenddeveloping** [comment]
@kdzwinel you have http request (http://ghbtns.com) in https mode. This throw error and getUserMedia API don't work.

**Comment by kdzwinel** [comment]
@frontenddeveloping ah, I missed that, thank you!

**Comment by greatbiodun1** [comment]
I download the JS_OCR run the index file for a test before using, its not working. can anyone guide me on the installation please?

**Comment by kdzwinel** [comment]
You can't just open the index file in your browser from your filesystem, you need a http server (e.g. https://www.npmjs.com/package/http-server ). Also make sure you are using localhost as your host, otherwise it won't work over http (it will require https to access camera).

**Comment by greatbiodun1** [comment]
ok, how can I configure my localhost to use https instead of http?

**Comment by kdzwinel** [comment]
if you use http://localhost, you can use http. If you use anything else, you have to use https.

**Comment by greatbiodun1** [comment]
Thanks you, it worked!. the text recognition is poor

On 26 April 2016 at 12:52, Konrad Dzwinel notifications@github.com wrote:

> if you use http://localhost, you can use http. If you use anything else,
> you have to use https.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/kdzwinel/JS-OCR-demo/issues/3#issuecomment-214715772

## 

Adegbuyi Abiodun Oluwaseun

Software Architect

08038141686

**Comment by kdzwinel** [comment]
Fix it! I'm using this library - http://antimatter15.com/ocrad.js/demo.html

**Comment by greatbiodun1** [comment]
is the OCRAD you are using the updated version?

On 26 April 2016 at 13:29, Konrad Dzwinel notifications@github.com wrote:

> Fix it! I'm using this library -
> http://antimatter15.com/ocrad.js/demo.html
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/kdzwinel/JS-OCR-demo/issues/3#issuecomment-214723374

## 

Adegbuyi Abiodun Oluwaseun

Software Architect

08038141686

**Comment by kdzwinel** [comment]
I havent' updated it in a while, please do that! You can create a PR when you will.
